### ISSUE TITLE
Add degrees 1 to 4

### ISSUE THREAD

**Issue by fingolfin** [gap-packages/QuimpGrp#13]
Currently:
```
gap> NrQuimpGroups(3);
Error, Quimp groups are only known for degree between 5 and 4095
```
But why? The primitive groups are available, surely there is no problem finding all quimps with degree $\leq 4$? (Presumably there are none?)

**Comment by glukemorgan** [comment]
@fingolfin 
There are no quimp groups of such degrees - every permutation group of degree ≤ 4 is soluble. Soluble quasiprimitive groups are of affine type, and the affine type quasiprimitive groups are primitive. Thus there are no "Quimp" groups of such degrees.

**Comment by fingolfin** [comment]
Yes exactly. So the relevant functions should accept these degrees and just treat them like other degrees with 0 quimps.
